### ISSUE TITLE
Where can I download the latest DLL？

### ISSUE THREAD

**Issue by bymomo** [leplexion/Lep_Ahk2.py#1]
Does the DLL need to get compilation from the source code warehouse?

**Comment by leplexion** [comment]
no need,i put dll is in "/bin" folder

**Comment by leplexion** [comment]
you can download new dll from 
https://github.com/HotKeyIt/
Hotkeyit's repo
but Hotkeyit may change the dll export api.. im not sure other version will work via my py lib.
